name: UnZipper
run-name: "UnZipper By MrF1yn. Pushed B: ${{ github.actor }}"
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - run: unzip -o modpack.zip
      - run: rm modpack.zip
      - run: git config --local user.email "github-actions@users.noreply.github.com"
      - run: git config --local user.name "github-actions"
      - run: git add .
      - run: git commit -m "unzip"
      - run: git push origin main