name: Unarchive and Commit
run-name: "UnZipper By MrF1yn. Pushed B: ${{ github.actor }}"
on: [published]
jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - run: unzip -o *.zip
      - run: rm *.zip
      - run: git config --local user.email "github-actions@users.noreply.github.com"
      - run: git config --local user.name "github-actions"
      - run: git add .
      - run: git commit -m "$commit_message"
      - run: git push origin main
