name: learn-github-actions
run-name: UnZipper By ${{ github.actor }}
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq modpack.zip    